### ISSUE TITLE
What https://blog.openstreetmap.org/2022/06/02/announcement-data-model-study/ will cover?

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/osm-data-model#7]
Is it just about adding node position info to ways or also about other changes like - for example - area datatype?

**Comment by mmd-osm** [comment]
One meta topic that immediately comes to mind is the overall API versioning strategy (https://github.com/openstreetmap/openstreetmap-website/pull/2353). It would be good if non compatible (=breaking) changes on API level would include a discussion on migration aspects as well (the "how do we get there?").

In general, I'm not exactly clear on the list of ideas you've planned to consider, which provider/consumer apps are in focus, and the overall methodology to assess impact, cost, feasibility. If you have some really high level sketch that would be really helpful to understand the big picture a bit bitter.

**Comment by matkoniecz** [comment]
> If you have any topics, please raise them

Area data type instead of multipolygon hack and "this line can be area or area and line at once, depending on tags and depending on who will decide that".

Estimating costs of introducing such incompatible change (updating editors, at least adding adapters for existing data consumers)

Ensuring that changes, if made, will not make things easier for data consumers at cost of mappers.

**Comment by joto** [comment]
Here is the offer I sent to EWG in January of this year which was later accepted by EWG. I hope this sheds some more light on what's planned and what the approach is.

# A possible next step towards OSM data model changes

At the end of 2021 Tobias Knerr talked to me (Jochen Topf) about the revived
EWG and its interest in maybe pushing OSM data model changes, possibly, but not
necessarily, in the direction I talked about in my talk at SoTM 2018 in Milan
[1].

Many of the proposed changes (or similar ones) would need a huge and concerted
effort on the part of the OSM community over several years involving many
players. And if we stop half-way, the effort is in vain. So far nobody has been
willing and able to tackle this project. I believe this is something we can do
as a community, but only if there is some common agreement that we *want* to
tackle it. And we need funding for it. The scope is much larger than anything
anybody could do in their spare time. The effort will need some kind of project
management, some people to come up with documentation, specs, plans. And it
also needs the support of many implementors in many Open Source and proprietary
projects. Not all of them will be able to handle this on their own, they will
need support and, maybe, also funding. All of this will not come cheap. In my
estimation we are surely looking at a six figure sum over several years.

As a step forward I can offer to write a study which looks at current proposals
and do a first evaluation of the expected problems and benefits of each
proposal, the changes and efforts needed, and come up with some kind of
timeline and project plan. This can not be complete, because nobody knows all
the software out there which uses OSM data, but it can look at the effort
needed for OSMF infrastructure and the most important pieces of software used
in OSM stacks. The study would be mostly based on my expertise and some limited
input from other people in the community, to get it done with a reasonable
amount of effort and cost. After that, the EWG can talk about it and decide
whether it wants to go forward with this project, what plan to adopt and how to
fund the effort.

For the study I estimate an effort of 120 hours of work. I offer this for the
fixed net price of 9600 EUR. Payment of the full sum after delivery of the
study. The study will be finished three months after placing of order. This
offer is valid until the end of March 2022.

[1] https://media.jochentopf.com/media/2018-07-30-talk-sotm2018-data-model-en-slides.pdf

**Comment by matkoniecz** [comment]
So it is from some discretionary funds open to anyone willing to submit a proposal, right? And received proposals are rejected/accepted by EWG based on what they consider as worth funding?

Or is there some bidding/offer/feedback stage open to people in general?

**Comment by tordanik** [comment]
> Or is there some bidding/offer/feedback stage open to people in general?

For many EWG projects, there will be a public request for bids, and the deliverable will be the implementation of some set of features. We have documented the approach we plan to follow for such projects in our [project funding framework](https://wiki.osmfoundation.org/wiki/Engineering_Working_Group/Project_Funding_Framework).

This particular project worked differently. Because we can't possibly hope to jump right into implementing it, decided we wanted someone to do some preliminary research and drafting as a first step. And due to Jochen's well-received prior work on the topic, some encouraging past successes such as the MP cleanup, and his involvement with relevant software projects, we approached him directly and encouraged him to submit an offer.

**Comment by ImreSamu** [comment]
>"The study will be finished three months after placing of order. "
>"Also about other stuff. If you have any topics, please raise them."

As an OSM data user, I would probably have some suggestions myself, but I need some time to develop and check them.

If I understand it correctly, I have a maximum of 1 month to submit it here and have a chance of getting it into the study (even if it is not ultimately proposed for adoption.)
Or do I have less time?

**Comment by joto** [comment]
The study is now available [here](https://media.jochentopf.com/media/2022-08-15-study-evolution-of-the-osm-data-model.pdf). Official publication by the EWG will come later. I'll also do a talk at SotM and there will be a BoF there to discuss things.

**Comment by matkoniecz** [comment]
@joto Is this text openly licensed? CC-BY-SA-4.0 for example?

If not, can it become openly licensed?

**Comment by matkoniecz** [comment]
> On the other hand, for tag values they might be too short for some of things we are doing with them.39 But we have been living with them for a long time and haven’t seen any problems

Complex `opening_hours` can run into such limits, and there are repeated questions from mappers how to handle https://wiki.openstreetmap.org/wiki/Key:inscription not fitting entire inscription.

See https://github.com/openstreetmap/openstreetmap-website/issues/2025 for example.

Likely not worth touching in isolation, but in case of backward incompatible changes it should be at least considered.


EDIT: moved to https://github.com/osmlab/osm-data-model/discussions/13#discussion-4340946

**Comment by joto** [comment]
Please don't start discussions in thiis issue now about specific issues from the paper. That will just create a huge mess. We'll find a way of organizing discussions.

**Comment by matkoniecz** [comment]
OK, then I am waiting for opportunity to comment on this and few other things. I marked it as off-topic in meantime.

Please mention here once giving feedback is welcome!

**Comment by joto** [comment]
I have set up [discussions](https://github.com/osmlab/osm-data-model/discussions) here in the repository where discussions related to the study and also general discussions about the data model can happen. We'll see how this goes, maybe the EWG will set up a different, more permanent solution for these discussions, but for the time being, that's what we have. I encourage everybody to participate there.

**Comment by joto** [comment]
> Is this text openly licensed?

I have updated the paper and added a CC-BY-SA license.

**Comment by joto** [comment]
I am closing this issue here because it contains a mixture of lots of things and isn't really useful in that form. Please use the [discussions](https://github.com/osmlab/osm-data-model/discussions) and start individual discussions there.
